name: Generate snake animation

on:
  schedule: 
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: 899-12
          outputs: dist/github-contribution-grid-snake.gif

      - name: Push generated GIF to output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.gif
